### ISSUE TITLE
Transaction State and Codes

### ISSUE THREAD

**Issue by pigmonkey** [ledger/vim-ledger#10]
According to [the docs](http://ledger-cli.org/3.0/doc/ledger3.html#Transaction-and-Comments), the transaction state should come before the transaction code.

```
DATE[=EDATE] [*|!] [(CODE)] DESC
```

A transaction using a code to indicate a check number would look like this:

```
2013/08/13 (#1234) Landlord Inc
    Expenses:Rent                            $999.99
    Assets:Bank:Checking
```

Then when marked as cleared, it should look like this:

```
2013/08/13 * (#1234) Landlord Inc
    Expenses:Rent                            $999.99
    Assets:Bank:Checking
```

Unfortunately, both `ledger#transaction_state_set` and `LedgerSetTransactionState` place the transaction state indicator between the code and the payee. Both functions result in a transaction that looks like this:

```
2013/08/13 (#1234) * Landlord Inc
    Expenses:Rent                            $999.99
    Assets:Bank:Checking
```

`ledger` does not recognize the above transaction as being cleared, but instead thinks that it is an uncleared transaction made to the payee `* Landlord Inc`.

**Comment by pickfire** [comment]
Is there any way that allows me to indent the currency to the right?
