### ISSUE TITLE
Error when opening a file whose path contains spaces

### ISSUE THREAD

**Issue by redneb** [ledger/vim-ledger#110]
When I try something like this:
```
mkdir /tmp/foo\ bar
privvim /tmp/foo\ bar/test.journal
```
then vim reports an error on startup:
```
Error detected while processing /home/user/.vim/pack/bundle/start/vim-ledger/compiler/ledger.vim:
line   31:
E518: Unknown option: bar/test.journal'\ print\ \ >\ /dev/null)
```

**Comment by alerque** [comment]
Thanks for reporting this. Clearly path quoting isn't happening as it should.

I'd be happy to accept a PR if anybody wants to fix this. I probably won't get to it myself very soon.
