### ISSUE TITLE
`makeprg` incorrectly set to `(hledger -f g:ledger_main::S print  > /dev/null)`

### ISSUE THREAD

**Issue by gregorias** [ledger/vim-ledger#121]
Since #119 vim-ledger incorrectly sets `makeprg` to `(hledger -f g:ledger_main::S print  > /dev/null)` in Neovim.

The root cause is that the expansion works differently between Vim and Neovim. Also, `::S` suffix only works if `g:ledger_main` is a special wildcard. Was that the intention? 

For addressing this issue, we could do one of the following:

1. Roll back #119, because it's a breaking change. 
2. Change to `expand(g:ledger_main . '::S')` if `g:ledger_main` being a wildcard is intended. This works in both Vims.
3. Check for Neovim and do 2. for Neovim only.
4. Let users configure the expanded filename by themselves.
5. Ignore, because you don't care about supporting Neovim.

**Comment by BackSeat** [comment]
I see exactly this problem with Vim 8.2 - I don't have Neovim installed.

Patch 241a879 fixes it for me.

**Comment by alerque** [comment]
Closed by #122.
