### ISSUE TITLE
'build' system

### ISSUE THREAD

**Issue by holomorph** [ledger/vim-ledger#14]
Hi, a Makefile for this plugin would be nice.  Here's one I wrote:

```
PREFIX      = /usr/local
datarootdir = $(PREFIX)/share
vimdir      = $(datarootdir)/vim/vimfiles

CP    = install -p -m644
MKDIR = install -p -m755 -d

install: install-doc install-plugin

install-doc:
    $(MKDIR) $(DESTDIR)$(vimdir)/doc
    $(CP) doc/ledger.txt $(DESTDIR)$(vimdir)/doc/ledger.txt

install-plugin:
    $(MKDIR) $(DESTDIR)$(vimdir)/{autoload,compiler,ftdetect,ftplugin,indent,syntax}
    $(CP) autoload/ledger.vim $(DESTDIR)$(vimdir)/autoload/ledger.vim
    $(CP) compiler/ledger.vim $(DESTDIR)$(vimdir)/compiler/ledger.vim
    $(CP) ftdetect/ledger.vim $(DESTDIR)$(vimdir)/ftdetect/ledger.vim
    $(CP) ftplugin/ledger.vim $(DESTDIR)$(vimdir)/ftplugin/ledger.vim
    $(CP) indent/ledger.vim   $(DESTDIR)$(vimdir)/indent/ledger.vim
    $(CP) syntax/ledger.vim   $(DESTDIR)$(vimdir)/syntax/ledger.vim

.PHONY: install install-doc install-plugin
```

**Comment by alerque** [comment]
I do appreciate you making the effort to contribute @holomorph, but I'm going to have to agree with the comments from PR #15 that installation for plugins is typically done differently than this and any attempt at a makefile would only mislead users on how it should normally be installed.

The current README could use wording improvements (contributions welcome!) but it does point to using a plugin manager which, especially at this date, seems to be the generally accepted wisdom on how to handle the "installation" problem.
