### ISSUE TITLE
foldtext incorrectly takes balance assertions as txn value

### ISSUE THREAD

**Issue by jmtd** [ledger/vim-ledger#153]
Given a transaction such as

```
2024-03-09 ebay payout
    assets:nationwide    £ 13.15 = £ 126.86
    io:income:ebay
```

the foldtext looks like 

```
2024-03-09 ebay payout                                                   126.86
```

However, the correct amount for the transaction is £ 13.15 : £126.86 is balance assertion.

**Comment by alerque** [comment]
Contributions welcome.

I'm a little unsure about how you'd go about handling both regular transactions with incidental balance assertions and also dedicated balance assertion transactions, but if you come up with something I'm happy to facilitate things getting merged.

**Comment by jmtd** [comment]
> I'm a little unsure about how you'd go about handling both regular transactions with incidental balance assertions and also dedicated balance assertion transactions,

Was my example an instance of the former?  I don't think I've seen the latter. I'll have to check the docs (FWIW, I use hledger, so I will check the ledger docs/spec as well)

**Comment by alerque** [comment]
Yes your example is the former. An example of the latter in `hledger` would be to just assert the balance without actually moving anything between accounts. This is useful to add a reconcile point without tracking the balance on any actual transactions.

```ledger
2024-03-09 Balance assertion check point
    (assets:nationwide)    == £ 126.86
```

Note *that* example uses the `==` syntax that indicates there are no other currencies in the account, but that isn't a unique identifying feature of these kind of transactions. They might just as well have `=` or even more than one posting.

```ledger
2024-03-09 Balance assertion check point
    (assets:nationwide)    = £ 126.86
    (assets:nationwide)    =  $ 42.42
```

**Comment by alerque** [comment]
Perhaps the answer here is to always include the whole section after the account name and before any comments. This might include currency identifiers, amounts, balance assertions, and rates.

**Comment by alerque** [comment]
Yup, that was my thought.

I haven't looked at the code either, but rather than trying to parse for the amount it is probably going to be more robust to parse *out* the parts we know don't belong. We want everything after two spaces and before a comment marker (trimmed of course).

**Comment by jmtd** [comment]
For completion's sake, this is what the two forms of balance assertion transactions from https://github.com/ledger/vim-ledger/issues/153#issuecomment-1997491424 look like folded (after #154 ):

source

```
2024-02-29 balance assertion checkpoint
    (assets:monzo)    == £ 218.79

2024-02-29 balance assertion checkpoint 2
    (assets:monzo)    == £ 218.79
    (liabilities:amex)  == £ 0
```

result

```
2024-02-29 balance assertion checkpoint                                  218.79
2024-02-29 balance assertion checkpoint 2                                218.79
```

I think, by lucky coincidence, that's probably the best thing to do in the absence of any finer controls/preferences of how to display them.
