### ISSUE TITLE
Option to disable warning when ledger binary is not found

### ISSUE THREAD

**Issue by hrj** [ledger/vim-ledger#29]
Hi and thanks for this vim script.

I am using it mostly for syntax-highlighting. I don't have ledger installed on my system, and I don't need any of the advanced features (error-checking, auto-formatting, etc).

Everytime I open a `.ledger` file, I get a warning:

```
ledger command not found. Set g:ledger_bin or extend $PATH to enable error checking and auto-formatting.
```

Would be nice to have an option that disables this warning.

**Comment by kljohann** [comment]
Ye, we should probably change this so this message only occurs when one actually tries to run a command that needs ledger.

**Comment by hrj** [comment]
@lifepillar I see that you have many changes in your fork that haven't been merged into this repo yet (despite your pull requests). I don't know vimscript and can't create issues on your fork, so can you tell me:

* is your fork's master branch good for general us?
* How can this warning be disabled / delayed?

**Comment by lifepillar** [comment]
@hrj My fork is only two commits ahead of the official repo, but those are relatively minor changes. So my fork is essentially as good as the official one, and I would recommend keeping using the official one.

>How can this warning be disabled / delayed?

You may try commenting out lines 29–32 in `ftplugin/ledger.vim`.

**Comment by alerque** [comment]
While testing to see if this was still a bug, I noticed that changing `g:ledger_bin` to a bogus value does _not_ trigger this bug. It seems the plugin is silently falling back on `ledger` if the other executable is not found. I think this is highly undesirable behavior as in workflows like mine that _depend_ on `hledger` instead should not be processed by `ledger`, they should error if `hledger` is not found. This issue can probably be addressed at the same time as the main issue above.

**Comment by alerque** [comment]
I have added an option to cover this (as well as previously fixed my own gripe above).

The option covers two use cases:

* Your use case @hrj of not having `ledger` or `hledger` and wanting to skip the warnings.
* The alternative of *having* a ledger command but specifically _not_ wanting to enable any of the features that call them.

Either way use it like this:

```vim
let g:ledger_no_bin = 1
```

This will stop trying to find one and not warn that the setting is not set.
