### ISSUE TITLE
foldmethod from modelines don't work

### ISSUE THREAD

**Issue by rstacruz** [ledger/vim-ledger#31]
I'd like to have this modeline for my files:

```
; vim:foldmethod=marker
```

Unfortunately it doesn't work. ftplugin/ledger.vim presumably overrides it.

**Comment by kljohann** [comment]
You are right, ledger should probably not set this. Instead we should put a note in the docs indicating the availability of syntax based folding.

**Comment by rohieb** [comment]
There is something strange going on here. With my change in #60, even if I set `foldmethod=marker` in my modeline, it doesn't get applied, and `:set foldmethod?` prints `foldmethod=manual`.

However, when I set `filetype=foobar foldmethod=marker` in my modeline (or in fact any other filetype except `ledger`), my marker folds are neatly folded away, `:set foldmethod?` gives me `foldmethod=marker` – but `:set filetype?` also still gives me `filetype=ledger`…
