### ISSUE TITLE
formatprg setting remains

### ISSUE THREAD

**Issue by Boldewyn** [ledger/vim-ledger#38]
**How to reproduce:**
1. Have a file of any type open, note that `set formatprg?` returns the empty string
2. Open a ledger file in a new tab: `:tabe foo.ledger`. `formatprg` is set to the ledger binary.
3. Close the tab with the ledger file again.
4. In the first tab with the original file, `set formatprg` now shows `ledger -f -print`.

**What should happen?**

The setting of `formatprg` should be local to the buffer with the ledger file, not in any way global.

From reading `:help 'formatprg'` it seems, that `:setl` has no effect on `formatprg` (note the _'global'_), and it seems to have to be reverted manually, somehow.

**Which version do you use?**

Commit 726359d582adf066905e01ec0081a6d028be97a2, most current version.

**Comment by kljohann** [comment]
The best fix for this would probably involve reimplementing this feature via `formatexpr` (which is buffer-local and can thus be undone by `setl formatexpr<` in `b:undo_ftplugin`). I don't know when I'll get around to do this, so if anyone wants to work on this I would gladly accept a pull request.

**Comment by alerque** [comment]
This has been fixed for some time, probably as a side effect of when the plugin was rearranged to use autoload. The scope of this setting is now correct (tested in VIM & Neovim).
