### ISSUE TITLE
Support for neovim makeprg

### ISSUE THREAD

**Issue by pickfire** [ledger/vim-ledger#40]
By default, neovim's compiler is make so I think it is better to ignore if it's make. In my humble opinion, there is no reason to use make with ledger.

https://github.com/ledger/vim-ledger/blob/master/compiler/ledger.vim#L6

The current compiler will be make by default.

**Comment by pickfire** [comment]
If I am correct, you can just:
```vimscript
if exists("current_compiler") || current_compiler == "make"
```

**Comment by alerque** [comment]
I my humble opinion, you're wrong :wink:.

In fact my primary workflow for ledger files involves `make`. All the orgs I manage and my own personal finances have makefiles setup along with assorted ledger input files to generate various reports automatically based on what data files change.

There might be another way to support `makeprg` properly without just flat out ignoring `make` as a possible value. I'd be happy to hear anybody's input on that.

**Comment by alerque** [comment]
This appears to be obsolete. The `makeprg` value is being set dynamically to something involving the ledger binary if detected or set by the end user. This seems reasonable.

If there is anything else that could be done here please feel free to comment.
