### ISSUE TITLE
Extract date format to a configuration variable

### ISSUE THREAD

**Issue by moll** [ledger/vim-ledger#44]
Hey,

Giving plain text accounting a spin and enjoying it so far. Thank you for your contribution with Ledger.vim!

I'm focused on using ISO 8601 dash-separated dates everywhere. Would you consider extracting the `strftime` pattern Ledger.vim uses to a variable so I could configure it to use that instead of the default `%Y/%m/%d`?

Thank you!

**Comment by kljohann** [comment]
Implemented in 9850f4dd by @cgiacofei. Thanks to you both!
