### ISSUE TITLE
Release so I can upload vim-ledger to Debian?

### ISSUE THREAD

**Issue by EdwardBetts** [ledger/vim-ledger#45]
Hi,

I'd like to package vim-ledger for Debian. Packaging works best when based on a specific release. If you make a release of vim-ledger on github I'll work on the Debian package.

Thanks.

**Comment by kljohann** [comment]
I just tagged `v1.0.0`.

**Comment by EdwardBetts** [comment]
Package uploaded: https://tracker.debian.org/pkg/vim-ledger
