### ISSUE TITLE
change paragraph motion to move by transaction

### ISSUE THREAD

**Issue by rcaputo** [ledger/vim-ledger#48]
These commands replace the previous- and next-paragraph motion keystrokes with previous- and next-transaction.  I think this makes more sense in ledger files.

`noremap { ?^\d<CR>`
`noremap } /^\d<CR>`

Or you can add these to your .vimrc:

`au FileType ledger noremap { ?^\d<CR>`
`au FileType ledger noremap } /^\d<CR>`

**Comment by kljohann** [comment]
I keep empty lines between transactions to a similar effect. But I like your suggestion. Would you like to add it to the `tips` section of `doc/ledger.txt`?

**Comment by rcaputo** [comment]
See pull pull request #57.
