### ISSUE TITLE
Support for block comments

### ISSUE THREAD

**Issue by colemand77** [ledger/vim-ledger#54]
Seems that syntax highlighting for block comments
```
comment
some comments
go here
end comment
```
is not supported?

[This is the block comment format described in the ledger documentation](http://ledger-cli.org/3.0/doc/ledger3.html#Commenting-on-your-Journal)

I apologize I don't know Vimscript - I'd just submit a pull request for the feature if I did.  
If I can reason it out I'll submit one.

**Comment by alerque** [comment]
Support for block comments was added thanks to @rohieb in dbbfbc1 and merged as part of #63.
