### ISSUE TITLE
Input that goes to command lines needs quoting

### ISSUE THREAD

**Issue by rcaputo** [ledger/vim-ledger#58]
For example, the space in this account name breaks the ledger register command:

    :call ledger#reconcile("home.ledger", "Accounts Payable", 0)

Sample fix:

    diff --git a/autoload/ledger.vim b/autoload/ledger.vim
    index 04aa488..9ca66af 100644
    --- a/autoload/ledger.vim
    +++ b/autoload/ledger.vim
    @@ -607,7 +607,7 @@ function! ledger#reconcile(file, account, target_amount)
             \ "--sort '(amount < 0 ? amount : -amount), date, amount'",
             \ "--format='" . g:ledger_qf_reconcile_format . "'",
             \ "--prepend-format='%(filename):%(beg_line) %(pending ? \"P\" : \"U\") '",
    -        \ a:account
    +        \ "'" . a:account . "'"
             \ ]))
       let l:file = expand(a:file) " Needed for #show_balance() later
       call s:quickfix_populate(systemlist(l:cmd))

**Comment by alerque** [comment]
Thanks for reporting this and for the sample fix. Anybody that would like to systematically fix this for anywhere it might be an issue is invited to contribute a PR! I probably won't get around to it myself as I'm meticulous about not using spaces in accounts or anywhere else likely to cause such issues, so I won't need to scratch this itch personally but it would be great to see it fixed anyway.
