### ISSUE TITLE
Not an editor command: LedgerAlign

### ISSUE THREAD

**Issue by agarrharr** [ledger/vim-ledger#67]
I can't figure out how to get this plugin to work. When I run: `:LedgerAlign`, I get this error:

```
E492: Not an editor command: LedgerAlign
```

And in visual mode, when I run: `:'<,'>LedgerAlign`, I get the same thing:

```
E492: Not an editor command: '<,'>LedgerAlign
```

I've also tried running `:call ledger#entry()`, and I get:

```
Error detected while processing function ledger#entry:
line    1:
E121: Undefined variable: g:ledger_main
E116: Invalid arguments for function s:ledger_cmd(g:ledger_main, join(["entry", getli
ne('.')])))
E116: Invalid arguments for function systemlist(s:ledger_cmd(g:ledger_main, join(["en
try", getline('.')])))
E15: Invalid expression: systemlist(s:ledger_cmd(g:ledger_main, join(["entry", getlin
e('.')])))
line    3:
E121: Undefined variable: l:output
E116: Invalid arguments for function filter(l:output, "v:val !~? '^Warning: '")
E15: Invalid expression: filter(l:output, "v:val !~? '^Warning: '")
line   10:
E121: Undefined variable: l:output
E116: Invalid arguments for function append
```

**Comment by alerque** [comment]
Can you explain how you installed the plugin? It works fine for me (and many other people) so I'm assuming this has something to do with how you installed an initialized the plugin. Are you using a plugin manager?

**Comment by agarrharr** [comment]
It’s been a while, but I can try it again. I was using  vim-plug.

**Comment by alerque** [comment]
I'm also using `vim-plug` and haven't had any trouble, nor do I see confirmation of this being a general problem. If there is a problem I'd be happy to see it fixed, but at this point I'm not even sure where to start. If you can reproduce the issue, let us know.

**Comment by agarrharr** [comment]
It's working! 👍
