### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by robbat2** [ledger/vim-ledger#69]
Please make a new release.

**Comment by alerque** [comment]
Hey...I've just stepped in to lend a hand maintaining this plugin.

I have tagged [v.1.1.0](https://github.com/ledger/vim-ledger/releases/tag/v1.1.0) for release. Note the last development work was from 2017, so this is mostly a rollback point before I start doing more work. This should answer this issue, but...

I'm curious why this matters to you. Most plugin managers in the vim ecosystem I'm aware of default to tracking upstream master branches. What is your workflow that tagged releases are important? I'll keep any comments in mind for future release cycles.

**Comment by robbat2** [comment]
Actual distribution packages, in this case, the `app-vim` category in Gentoo:
https://packages.gentoo.org/packages/search?q=app-vim%2F
Upstream releases (or even upstream-chosen snapshots) are preferred over arbitrary snapshot points chosen by the distribution package maintainer.

**Comment by alerque** [comment]
Roger that @robbat2. In addition to last week's tag that was _before_ I started messing with this repository, I just tagged [v1.2.0](https://github.com/ledger/vim-ledger/releases/tag/v1.2.0) which has almost all the forks and user contributed stuff over the last couple years integrated again and a few other odds and ends touched up.
