### ISSUE TITLE
LedgerAlign inconsistently indents at 2 or 4 spaces

### ISSUE THREAD

**Issue by gavinedwards** [ledger/vim-ledger#70]
When using `LedgerAlign` it will sometimes set the space to 2 spaces.  For example, these two entries have each been set using the command:

    2018/07/25 Purchase 1
        Assets:Cash                                         $-9.90
        Expenses:Coffee                                      $9.90
    
    2018/07/26 Purchase 2
      Assets:Cash                                           $-2.15
      Expenses:Coffee                                        $2.15

Here are the ledger configuration lines from `.vimrc`

    let g:ledger_bin = 'ledger'
    let g:ledger_maxwidth = 80
    let g:ledger_fillstring = '    -'
    let g:ledger_detailed_first = 1
    let g:ledger_fold_blanks = 1
    let g:ledger_decimal_sep = '.'
    let g:ledger_align_at = 60
    let g:ledger_default_commodity = '$'
    let g:ledger_commodity_before = 1
    let g:ledger_date_format = '%Y/%m/%d'
    let g:ledger_main = '%'
    let g:ledger_winpos = 'B'
    let g:ledger_qf_reconcile_format = '%(date) %-4(code) %-50(payee) %-30(account) %15(amount)\n'
    let g:ledger_use_location_list = 0
    let g:ledger_qf_vertical = 0
    let g:ledger_qf_size = 20
    let g:ledger_qf_hide_file = 1
    let g:ledger_cleared_string = 'Cleared: '
    let g:ledger_pending_string = 'Cleared or pending: '
    let g:ledger_target_string = 'Difference from target: '

**Comment by alerque** [comment]
According to the documentation the align function "moves the amount expression of a posting [...]". It was not intended to reformat the account field or change indentation preferences.

I suggest you start by making sure vim is configured to the size you want, e.g. `:set ts=4 sw=4 et` for four space indents, then use vim's normal indentation features.

The feature you are looking for is probably the format paragraph command (try selecting your transaction in visual mode and triggering the rewrite with `ga`). This will normalize the leading spacing on postings like you expect.
