### ISSUE TITLE
Project status, devel & issue triage

### ISSUE THREAD

**Issue by alerque** [ledger/vim-ledger#75]
I am a long time VIM user (exclusive editor for 20+ years, currently using Neovim) and brand new Ledger user (20+ hours). I've started the processes of migrating both my personal and several organization's finances into Ledger format. While both `ledger` and `hledger` feel very refined and productive, the experience from this vim plugin out of the box is pretty lackluster. It does help in a lot of ways, but it's pretty rough around the edges.

It also looks like development has [stagnated](https://github.com/ledger/vim-ledger/pulse/monthly). The last commit was in 2017, and  quite a number of Pull Requests and Issues have gone untouched. Some of the PR's are clearly _not_ in shape to be merged, but at least a couple of them look like they could be included pretty easily. In any event, not even replying to PRs and not merging the good ones is a good way to shut down community involvement and discourage future contributions.

A quick scan shows that the Emacs side of things is a lot more active with the [ledger-mode](https://github.com/ledger/ledger-mode) repository having a lot of [activity](https://github.com/ledger/ledger-mode/pulse/monthly). I would like to help revive the vim side of things a bit by having a developer actively interested in it with Github Contributor access.

I hereby request access to this repository with the goal of triaging issues, overseeing PRs, cleaning up the rough edges, and generally fostering the development process.

I have previously taken over maintenance of the popular [nerdcommentor](https://github.com/scrooloose/nerdcommenter) plugin when it stagnated. You can poke around the history there to see how that's gone. More recently I've also started helping with  [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) and [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax). You can review how my contributions have been received there.

**Comment by alerque** [comment]
Any feedback on this? Gently nudge to @jwiegley (because it looks like you might be the owner of the Github org this repository is under), @simonmichael (because you have a little context for knowing who I am from HLedger issues), and @tlvince and @kljohann (because you two have the most previous commits to the repository). I don't know who actually can make this decision or has access to the repository access settings, but I'm hoping one of you at least knows what I should do next.

Thanks for the consideration.

**Comment by simonmichael** [comment]
@alerque I don't know either, but if you can track down @kljohann's email or other contact info.. if not, there's forking..

**Comment by kljohann** [comment]
First of all thanks for the offer to help maintaining the ledger plugin for vim! I also only joined as a contributor when the vim support files were still located in the main ledger repository and helped out to coordinate development on the vim-ledger repo since. So I would not see myself as the "owner" of this repository in any way. In fact, vim-ledger has been fulfilling my needs w.r.t. ledger support for quite some time and while I also appreciate any new features and fixes as a user of the plugin, I did not have the time recently to actively track and contribute to its development. ( The fact that GitHub does not send notifications for new PRs but only when I'm explicitly mentioned certainly does not improve my response times, I guess. ;) )
I have also been thinking that it would be nice if someone else helped out, and I think @jwiegley would gladly accept new contributors to this repository.
Also pinging @rcaputo (who set up rcaputo/vim-ledger_x as I saw just now), @lifepillar and @rohieb, who were frequent contributors in the "recent" past. :)

**Comment by lifepillar** [comment]
I am still using this plugin regularly. It may not have been updated recently, but it works (except for an occasional issue with completion which I have never bothered to debug)!

It would be nice to have this plugin actively maintained, but I do not have time for such a commitment. As long as I am using it, however, I'd be happy to try new releases and provide feedback!

**Comment by rcaputo** [comment]
Thanks for the ping.

I haven't contributed lately for a couple reasons.  I'm mostly satisfied with vim-ledger, and vim-ledger_x lets me fill in the rest.  Some of my past ideas have been met with resistance.  That's reasonable, but it leads me to believe that I may not be qualified to resolve issues or merge pull requests, let alone design and implement new features.

**Comment by alerque** [comment]
@kljohann Thanks for your response! Please disregard the email I sent you, that was sent before I refreshed this issue page and saw the response here.

@simonmichael I'll fork if that's what it takes (if nothing else to meet my own needs) but I really believe the open source model works best when the original projects stay open to community led development, and I figure I'd give that route the best chance first. A fork could always be integrated later, but particularly with many open issues and PRs here it would be less confusing in the long run if I could just start where this left off rather than trying to gather steam somewhere else.

@rcaputo I was not previously aware of your extensions repository but will have a look at your work as well!

**Comment by jwiegley** [comment]
I'm pretty much unrelated to this project, so it'll be up to the authors to determine how they want to proceed.

**Comment by alerque** [comment]
Hey @jwiegley and thanks for chiming in here. The lion's share of the authoring to date was done by @kljohann, and he has already stated this:

> I have also been thinking that it would be nice if someone else helped out […]

But it seems he's had to defer to you because you have control of the Github org where settings are controlled such as adding/removing members.

**Comment by jwiegley** [comment]
Oh! I just now added him as the maintainer for that repository. Please let me know if he needs any further access.

**Comment by alerque** [comment]
That's cool and all @jwiegley, but he wasn't the one offering! I was. And if I'm reading [his comments](https://github.com/ledger/vim-ledger/issues/75#issuecomment-504772767) correctly he endorsed the idea of having somebody _else_ maintain it, suggesting you might be willing to add me.

@kljohann Does this change give you the ability to add other maintainers (and could you thus add me) or does that still need to be done at the org level? Maybe you can speak into this a little bit more directly, there seems to be some misunderstanding.

**Comment by kljohann** [comment]
Thanks John! Unfortunately I'm not able to add any new members/contributors to the repository. It seems this has to be done at the @ledger org level. (I now have access to a "Settings" tab for the vim-ledger repository, but it only contains options to turn off "Wiki" and "Projects" for this repo.)
So maybe a vim-ledger specific "team" has to be set up at the @ledger org level and given permissions for this repo?

**Comment by jwiegley** [comment]
@kljohann I've created `Vim-Ledger Hackers`, made it a `Write` access team for `ledger/vim-ledger`, and added you as a maintainer of the group. So, you should be able to add people to the group, which will give them rights to push to the repository.

**Comment by kljohann** [comment]
@jwiegley Thanks, that should work. However, as `Vim-Ledger Hackers` is a sub-team of `Ledger Hackers`, it also grants Admin permissions on the ledger, ledger-mode and ledger-website repositories. That's probably not intentional, right?

**Comment by jwiegley** [comment]
It shouldn't give Admin writes, but it will give Write permission. I guess I should reorganize that...

**Comment by alerque** [comment]
Hey @kljohann if you have access to add collaborators on this project now would you consider adding me?

**Comment by kljohann** [comment]
@jwiegley Thanks again for setting up the Vim-Ledger Hackers team. As it got re-created as a standalone top-level team, I do not have permissions yet to add new members. Could you either take a second look into the permissions or directly add @alerque as a member?

**Comment by jwiegley** [comment]
@kljohann Made you a maintainer, and invited @alerque.

**Comment by alerque** [comment]
Thank you! I can confirm the invite came through. It's Sunday now but I expect to start working through issues and reviewing PRs later this week.
