### ISSUE TITLE
Comments after postings (same line)

### ISSUE THREAD

**Issue by kljohann** [ledger/vim-ledger#8]
Comments after posting do not have to be preceeded by whitespace:

```
2013/01/01 Test  ; ← needs whitespace
  A  5€; ← doesn't need whitespace
  B
```

**Comment by alerque** [comment]
I was just verifying this bug and comparing the behavior of comments between `ledger` and `hledger` (to which incidentally I've recently contributed [a change related to comment spacing](https://github.com/simonmichael/hledger/pull/1048)) and am curious about Ledger 3's behavior. Does it always move posting comments to their own lines? Running your test through `ledger -f- print` I get:

```ledger
2013/01/01 Test  ; ← needs whitespace
    A                                             5€
    ; ← doesn't need whitespace
    B
```

Is that universal or are line level comments an option somehow?
