### ISSUE TITLE
Add function to set state of posting instead of just whole transaction

### ISSUE THREAD

**Issue by kcwu** [ledger/vim-ledger#81]
By Ledger's design, users can reconcile transactions by marking transactions and/or postings.

`ledger#transaction_state_set` can set state mark to transactions. 
Feature request: provide another function which can set state mark to posting at given line.

**Comment by alerque** [comment]
Pull requests welcome!

**Comment by kcwu** [comment]
https://github.com/ledger/vim-ledger/pull/112
