### ISSUE TITLE
Folded text fails to account for double-width characters

### ISSUE THREAD

**Issue by lolilolicon** [ledger/vim-ledger#82]
Unfolded texts:

```
2019/08/26 made1k
    assets:cash                                       $1000
    income:work
```

vs.

```
2019/08/26 一千元
    assets:cash                                       $1000
    income:work
```

Folded texts:

```
2019/08/26 made1k                                     1000 |EOL
```

vs.

```
2019/08/26 一千元                                        10|EOL
```
Note how the amount in second folded text is shifted to the right by 3 characters, which is exactly what would happen if vim-ledger were treating the 3 double-width characters as single-width ones.

**Comment by lolilolicon** [comment]
I looked into this, and seem to have found a fix:
```diff
diff --git a/ftplugin/ledger.vim b/ftplugin/ledger.vim
index 93532d0..b82d6e2 100644
--- a/ftplugin/ledger.vim
+++ b/ftplugin/ledger.vim
@@ -225,6 +225,9 @@ function! LedgerFoldText() "{{{1
     let foldtext .= repeat(' ', s:get_columns())
   endif
 
+  " account for multibyte characters in the following substitution
+  let columns -= strdisplaywidth(foldtext) - strchars(foldtext)
+
   " we don't use slices[:5], because that messes up multibyte characters
   let foldtext = substitute(foldtext, '.\{'.columns.'}\zs.*$', '', '')
 
```
Note though the name `columns` is not correct any more here.
Please consider, thanks.

**Comment by alerque** [comment]
Thanks for tracking down where this needs to be fixed! Of course we'll consider it. In fact if you write this up as a PR I'm sure we can get it reviewed and merged.

**Comment by lolilolicon** [comment]
My fix is in fact incorrect. It will fail as soon as any of the cut-off text in `foldtext` is double-width.
We probably need to change the calculation algorithm a bit to sort this out.
