### ISSUE TITLE
Unable to set ledger binary

### ISSUE THREAD

**Issue by anjannath** [ledger/vim-ledger#83]
I am using `hledger` and would like to set it using `g:ledger_bin`, but when add it to my `.vimrc`, there are errors:
```
"2019-Sept.journal" [New File]
Error detected while processing /home/noone/.vim/plugged/vim-ledger/compiler/ledger.vim:
line   28:
E121: Undefined variable: g:ledger_extra_options
E116: Invalid arguments for function substitute(g:ledger_extra_options, ' ', '\\ ', 'g').'\ source\ %:S'
Press ENTER or type command to continue
```

```
let g:ledger_bin = '/usr/bin/hledger'`
```

**Comment by gainhad** [comment]
Do you have `g:ledger_extra_options` set? I set it to an empty string and that fixed the issue for me.

**Comment by alerque** [comment]
Thanks for noting that @gainhad, if that's really the case that's clearly a bug. It shouldn't require that option to be set.

**Comment by alerque** [comment]
@gainhad The workaround you describe seems to be contraindicated by this code:

https://github.com/ledger/vim-ledger/blob/2dbe0ea244048a442a68b3e976936f73987d3d3c/ftplugin/ledger.vim#L43-L45

In other words the plugin is already setting it to an empty string if it is not set. The only way your workaround would fix anything is if your configuration was setting it to something invalid first, then clearing it would help. Not being set at all should not be an issue.

I still don't know what the problem is here, but that doesn't seem to be it.

**Comment by alerque** [comment]
@anjannath and @gainhad I'm wondering if you guys even have the ledger file type set properly. The only way I can think of to get that error is if you try to call a function of the plugin (the source of which will autoload) before having loaded the filetype definition (which sets up those variables).

When you open one of your journals, what is the output of `:set ft`?

**Comment by gainhad** [comment]
@alerque `:set ft` outputs `filetype=ledger`

I think I might know the issue. `:help ledger-tips` recommends setting `g:ledger_bin` in the `.vimrc`, which results in errors unless `g:ledger_extra_options` is set. If I set `g:ledger_bin` in `/after/ftplugin/ledger.vim` instead, then `g:ledger_extra_options` does not need to be set and there are no errors.

**Comment by alerque** [comment]
@gainhad That's some sort of race condition, `vimrc` should be the correct place to set that.

Thanks for the info though.

**Comment by gainhad** [comment]
@alerque No problem. Let me know if there's any other info that might be useful.

**Comment by alerque** [comment]
@anjannath and @gainhad this should be fixed now, please let me know if it gives you any trouble. If you don't need `g:ledger_extra_options` for anything you should be able to drop it from you rc files with no trouble. Also in #88 I tweaked a few things so detecting `g:ledger_bin` is a little more robust and you may or may not need to set it manually. Again feel free to raise issues if you have any.
