### ISSUE TITLE
Problem running :make - "please use -f"

### ISSUE THREAD

**Issue by dustinfarris** [ledger/vim-ledger#99]
When I run `:make` I get

```
:!ledger  source '/Users/dustin/Desktop/blah.php.journal'  2>&1| tee /var/folders/4g/6zr
14n815m715cq6nxv15d700000gn/T/nvimVSj3w3/1
Error: No journal file was specified (please use -f)
```

**Comment by alerque** [comment]
Obviously throwing an error is wrong, but out of curiosity what exactly would you expect to happen in this case? What would you expect `:make` to do? My inclination to fix this is to disable the compiler setting entirely rather than fix the arguments because I'm not sure what the default output should be.

**Comment by dustinfarris** [comment]
I was expecting some kind of output that `ledger source` would give.  It seems that it is missing the `-f` in the command.

**Comment by alerque** [comment]
Fair enough, that sounds like a reasonable default. It will only work for `ledger`, not `hledger`, but that's okay we can set that up properly.

My question now is how is `ledger source` actually supposed to be used? I'm trying it manually first to know what to expect and even when run as `ledger -f test.ledger source` it hands waiting for STDIN. It seems to work okay if I pass it an empty string as in `ledger -f test.ledger source <<< ""`, but that seems ridiculous. Requiring both the `-f` parameter and a STDIN stream is goofy and smells like a bug in Ledger CLI.

Do you happen to know how that's supposed to work?

**Comment by alerque** [comment]
This is indeed an already reported [bug in Ledger CLI](https://github.com/ledger/ledger/issues/1682).

I suppose we can work around it by specifying the file twice as noted is possible in that report, although that feels kind of dirty.
